# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [1]:
%run initialise.py

ERROR:root:File `'initialise.py'` not found.


#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [97]:
print(np.__version__)


1.21.6


#### 3. Create a null vector of size 10 (★☆☆)

In [98]:
v = np.zeros(10)

#### 4. How to find the memory size of any array (★☆☆)

In [99]:
np.size(v)

10

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [3]:
python -c 'import numpy; numpy.info(numpy.add)'

SyntaxError: ignored

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [100]:
v = np.zeros(10)
v[5]=1
v

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [101]:
v = np.arange(10,50)
v

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [102]:
v = np.arange(100)
v = v [::-1]
v

array([99, 98, 97, 96, 95, 94, 93, 92, 91, 90, 89, 88, 87, 86, 85, 84, 83,
       82, 81, 80, 79, 78, 77, 76, 75, 74, 73, 72, 71, 70, 69, 68, 67, 66,
       65, 64, 63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49,
       48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [103]:
v = np.arange(9).reshape(3,3)
v

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [7]:
np.nonzero([1,2,0,0,4,0])

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [ ]:
v = np.random.rand(27)
v = v.reshape(3,3,3)
v

array([[[0.78006906, 0.15187961, 0.59644213],
        [0.01054671, 0.9930102 , 0.93806012],
        [0.61364612, 0.3526012 , 0.77764385]],

       [[0.86751464, 0.77289527, 0.43216808],
        [0.17302862, 0.77492734, 0.25774784],
        [0.55719483, 0.61897131, 0.52034349]],

       [[0.98546761, 0.67554737, 0.79580269],
        [0.34777702, 0.40654745, 0.56671505],
        [0.34693949, 0.81365559, 0.69340434]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [ ]:
v = np.random.random((10,10))
v.min()
v.max()


0.9826050963540077

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [ ]:
v = np.random.rand(30)
v.mean()


0.47213139320931735

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [ ]:
v = np.ones((10,10))
v[1:-1,1:-1] = 0
v


array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [39]:
v = np.ones((10,10))
v = np.pad(v, pad_width=1, mode='constant', constant_values=0)
v

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [40]:
print (0 * np.nan)
print (np.nan == np.nan)
print (np.inf > np.nan)
print (np.nan - np.nan)
print (np.nan in set([np.nan]))
print (0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [32]:
v = np.diag(np.arange(1, 5), k=-1)
v

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [31]:
v = np.ones((8,8))
v[1::2,::2] = 0
v[::2,1::2] = 0
v

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [67]:
v = np.unravel_index(100, (6,7,8))
v

(1, 5, 4)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [37]:
v = np.array([[1, 0],[0, 1]])
np.tile(v, (4,4))

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [56]:
v = np.random.randint(1,9,(5, 5))
v = v / np.linalg.norm(v)
v


array([[0.32051323, 0.20032077, 0.12019246, 0.28044908, 0.16025662],
       [0.24038492, 0.04006415, 0.16025662, 0.32051323, 0.24038492],
       [0.20032077, 0.16025662, 0.32051323, 0.32051323, 0.20032077],
       [0.16025662, 0.12019246, 0.24038492, 0.20032077, 0.04006415],
       [0.08012831, 0.04006415, 0.16025662, 0.04006415, 0.08012831]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [48]:
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [59]:
v1 = np.random.randint(1,9,(5, 3))
v2 = np.random.randint(1,9,(3, 2))
v3 = np.dot(v1,v2)
v3

array([[ 90,  83],
       [ 78,  61],
       [120, 100],
       [ 84,  82],
       [ 96,  90]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [70]:
v = np.arange(10)
v[(v > 3) & (v < 8)] *= -1
v

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9])

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [63]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [75]:
Z = np.array([1, 2, 3, 4])

print(Z)
print(Z**Z)
print(2 << Z >> 2)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)
print(Z<Z>Z)

[1 2 3 4]
[  1   4  27 256]
[1 2 4 8]
[False False False False]
[0.+1.j 0.+2.j 0.+3.j 0.+4.j]
[1. 2. 3. 4.]


ValueError: ignored

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [76]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


#### 29. How to round away from zero a float array ? (★☆☆)

In [84]:
v = np.where(v>0, np.ceil(v), np.floor(v))
v

array([1., 2., 3., 4.])

#### 30. How to find common values between two arrays? (★☆☆)

In [86]:
v1 = np.array([6, 5, 1, 2, 8])
v2 = np.array([8, 5, 4, 5, 1])
v3 = np.intersect1d(v1, v2)
v3

array([1, 5, 8])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [83]:
np.seterr(all="ignore")
print("))))))))")

))))))))


#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [79]:
print(np.sqrt(-1) == np.emath.sqrt(-1))


False


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [88]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)
print(yesterday)
print(today)
print(tomorrow)

2022-09-29
2022-09-30
2022-10-01


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [89]:
v = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(v)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [4]:
v1 = np.random.randint(1,9,(5, 5))
v2 = np.random.randint(1,9,(5, 5))
np.matmul((v1+v2),(-v1/2))

array([[-104.5, -146. ,  -97.5, -136.5, -126. ],
       [ -64.5, -120.5,  -78. , -109. , -102. ],
       [ -77.5, -114.5,  -75.5, -106.5, -100.5],
       [ -68. , -103. ,  -80. , -103. ,  -79. ],
       [ -75.5,  -95. ,  -67. ,  -88. ,  -93.5]])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [24]:
v = np.random.rand(1, 5)
v = v * 3.1
print(v - v%1)
print(v.astype(int))
print(np.floor(v))
print(np.trunc(v))



[[0. 2. 2. 2. 1.]]
[[0 2 2 2 1]]
[[0. 2. 2. 2. 1.]]
[[0. 2. 2. 2. 1.]]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [31]:
v = np.zeros((5,5))
v += np.arange(5)
print(v)


[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [33]:
def generate():
    for x in range(10):
        yield x
v = np.fromiter(generate(),dtype=int,count=-1)
print(v)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[0 1 2 3 4 5 6 7 8 9]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

#### 40. Create a random vector of size 10 and sort it (★★☆)

#### 41. How to sum a small array faster than np.sum? (★★☆)

#### 42. Consider two random array A and B, check if they are equal (★★☆)

#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)